name: publish
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        # username: ${{ github.actor }}
        # password: ${{ secrets.DOCKER}}
        username: ${{ github.ACTOR }}
        password: ${{ secrets.GHCR_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
        export GHCR_USERNAME=Suscription
        # export GHCR_TOKEN=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
        docker login ghcr.io --username $GHCR_USERNAME --password-stdin
        docker build . --tag ghcr.io/suscription/hello-docker-gcr-demo:latest
        # docker run ghcr.io/suscription/hello-docker-gcr-demo:latest
        docker push ghcr.io/suscription/hello-docker-gcr-demo:latest